# _config.yml
title: CS 'n AI Blog
email: weiyichen21@163.com
description: "My notes about CS and AI courses / explorations."
url: "https://owencalstroy.github.io"
baseurl: "/CSnAI-notes"


# 主题配置
theme: jekyll-theme-minimal

# 构建配置
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 插件配置
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor